spring:
  spring:
    sql:
      init:
        mode: always
      data-locations: classpath:db/migration.sql
    jpa:
      defer-datasource-initialization: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: post

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: temuchi500@gmail.com
    password: vvottpyezfoubusd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

server:
  port: 9090

secret-key: 984hg493gh0439rthr0429uruj2309h937gc763fe87t3f89723gf

