spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: post

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 175128033513-hssnq4hpb8h6erqti2hha0f7ljnmruse.apps.googleusercontent.com
            client-secret: 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
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 7070


