spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: post

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: temuchi500@gmail.com
    password: vvottpyezfoubusd
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 175128033513-hssnq4hpb8h6erqti2hha0f7ljnmruse.apps.googleusercontent.com
            client-secret: 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
      ddl-auto: update
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

server:
  port: 9090

secret-key: 984hg493gh0439rthr0429uruj2309h937gc763fe87t3f89723gf


